# infra/monitoring/prometheus.yml
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'openbank-backend'
    static_configs:
      - targets: ['openbank-backend-service.openbank.svc.cluster.local:80']
        labels:
          service: 'backend'
          environment: 'production'

  - job_name: 'openbank-frontend'
    static_configs:
      - targets: ['openbank-frontend.openbank.svc.cluster.local:80']
        labels:
          service: 'frontend'
          environment: 'production'

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance

  - job_name: 'mongodb-exporter'
    static_configs:
      - targets: ['mongodb-exporter:9216']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance

rule_files:
  - "alerts.yml"