apiVersion: v1
kind: Service
metadata:
  name: openbank-backend
  namespace: openbank
spec:
  selector:
    app: openbank-backend
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: http
  type: ClusterIP