apiVersion: v1
kind: Service
metadata:
  name: openbank-backend
  namespace: openbank
  labels:
    app: openbank
    component: backend
spec:
  selector:
    app: openbank
    component: backend
  ports:
  - port: 5000
    targetPort: 8080
    protocol: TCP
    name: http
  type: ClusterIP