apiVersion: v1
kind: ConfigMap
metadata:
  name: openbank-config
  namespace: openbank
data:
  NODE_ENV: "production"
  MONGO_DB_NAME: "openbank"
  JWT_EXPIRY: "24h"
  API_VERSION: "v1"
  REACT_APP_API_URL: "http://openbank-backend:5000/api"