apiVersion: v1
kind: Service
metadata:
  name: openbank-frontend
  namespace: openbank
spec:
  selector:
    app: openbank-frontend
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  type: ClusterIP