apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: openbank-network-policy
  namespace: openbank
spec:
  podSelector:
    matchLabels:
      app: openbank
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: openbank
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: openbank
    ports:
    - protocol: TCP
      port: 27017  # MongoDB
    - protocol: TCP
      port: 5000   # Backend
    - protocol: TCP
      port: 3000   # Frontend